name: Deploy Yumly API

on:
  push:
    branches: ["release"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build shadowJar
        run: ./gradlew buildFatJar

      - name: Copy jar to server
        run: |
          scp -i ${{ secrets.SERVER_SSH_KEY }} build/libs/yumly-api.jar ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/yumly-api.jar

      - name: Restart service
        run: |
          ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "sudo systemctl restart yumly-api"
